### ISSUE TITLE
All seems to work, but then this.... 'Unexpected end of input' when bundling

### ISSUE THREAD

**Issue by FoundationAwesome** [erikvold/chrome-tailor#22]
$ chrome-tailor run
Made /tmp/chromeTailor_1153MGTxSRa44wkt
Copied chrome-tailor loader
Copied chrome extension
Creating package.json...
Wrote package.json
Unhandled rejection SyntaxError: /tmp/chromeTailor_1153MGTxSRa44wkt/package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
...

**Comment by EllaShar** [comment]
It happened to me either! Tried to debug. I think the bug is in `mk-tmp-dir.js` in line 47.
You do `fs.writeFile` to write `package.json`. But this is async, and the writing does not happen by the time you try to use the file in `xpi.js`. So the solution is using `writeFileSync` instead.

**Comment by Dune-jr** [comment]
I'm having the same issue! Can't even get https://github.com/erikvold/google-chrome-extension-examples/tree/master/tutorials/getstarted to work :(

**Comment by plhery** [comment]
same here :/

**Comment by ghost** [comment]
Same here for me.

**Comment by timothe** [comment]
Same, can't get my head around that :cry:

**Comment by JetFault** [comment]
@EllaShar is correct, renaming `fs.writeFile` to `fs.writeFileSync` fixed it.
