### ISSUE TITLE
xpi cannot be created

### ISSUE THREAD

**Issue by Coding-Hen** [erikvold/chrome-tailor#31]
E:\lookup>chrome-tailor xpi
Made C:\Users\x\AppData\Local\Temp\chromeTailor_1928DzdPhGkWhLRf
Copied chrome-tailor loader
Copied chrome extension
Creating package.json...
Wrote package.json
Creating xpi...
Unhandled rejection SyntaxError: C:\Users\x\AppData\Local\Temp\chromeTailor
_1928DzdPhGkWhLRf\package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\x\AppData\Roaming\npm\node_modules\chrome-tailor\lib\xpi.js
:29:22
    at tryCatcher (C:\Users\x\AppData\Roaming\npm\node_modules\chrome-tailo
r\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (C:\Users\x\AppData\Roaming\npm\no
de_modules\chrome-tailor\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (C:\Users\x\AppData\Roaming\npm\node_module
s\chrome-tailor\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\x\AppData\Roaming\n
pm\node_modules\chrome-tailor\node_modules\bluebird\js\main\promise.js:224:10)
    at Async._drainQueue (C:\Users\x\AppData\Roaming\npm\node_modules\chrom
e-tailor\node_modules\bluebird\js\main\async.js:180:12)
    at Async._drainQueues (C:\Users\x\AppData\Roaming\npm\node_modules\chro
me-tailor\node_modules\bluebird\js\main\async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:UsersxAppDataRo
amingnpmnode_moduleschrome-tailornode_modulesbluebirdjsmainasync.js:15:1
4)
    at processImmediate [as _immediateCallback](timers.js:367:17)

**Comment by Joncom** [comment]
Solution can be found in #34.

**Comment by AggelosM** [comment]
I'm still getting error:

C:\Users\Amaklp\AppData\Local\Google\Chrome\User Data\Default\Extensions\obbibbi
pcnihedbpfpkpnoceejpppdbf\1.0_0>chrome-tailor run -b firefox
Made C:\Users\Amaklp\AppData\Local\Temp\chromeTailor_1584syYpkHzP1Rdw
Copied chrome-tailor loader
Copied chrome extension
Creating package.json...
Wrote package.json
Unhandled rejection SyntaxError: C:\Users\Amaklp\AppData\Local\Temp\chromeTailor
_1584syYpkHzP1Rdw\package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at C:\Users\Amaklp\AppData\Roaming\npm\node_modules\chrome-tailor\lib\run.js
:17:22
    at tryCatcher (C:\Users\Amaklp\AppData\Roaming\npm\node_modules\chrome-tailo
r\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (C:\Users\Amaklp\AppData\Roaming\npm\no
de_modules\chrome-tailor\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (C:\Users\Amaklp\AppData\Roaming\npm\node_module
s\chrome-tailor\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\Amaklp\AppData\Roaming\n
pm\node_modules\chrome-tailor\node_modules\bluebird\js\main\promise.js:224:10)
    at Async._drainQueue (C:\Users\Amaklp\AppData\Roaming\npm\node_modules\chrom
e-tailor\node_modules\bluebird\js\main\async.js:180:12)
    at Async._drainQueues (C:\Users\Amaklp\AppData\Roaming\npm\node_modules\chro
me-tailor\node_modules\bluebird\js\main\async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:UsersAmaklpAppDataRo
amingnpmnode_moduleschrome-tailornode_modulesbluebirdjsmainasync.js:15:1
4)
    at processImmediate [as _immediateCallback](timers.js:383:17)

C:\Users\Amaklp\AppData\Local\Google\Chrome\User Data\Default\Extensions\obbibbi
pcnihedbpfpkpnoceejpppdbf\1.0_0>

**Comment by Joncom** [comment]
@amaklp, this may be a silly question, but did you check the solution in #34?

**Comment by AggelosM** [comment]
@Joncom  If I understand the solution correctly, my mk-tmp-dir.js version is the updated one.

**Comment by Joncom** [comment]
@amaklp, yes, that is correct. However, I'm not quite sure what to tell you. It sounds like you're running the older unfixed version of `chrome-tailor`...

**Comment by AggelosM** [comment]
@Joncom  I doubled check. I use the correct version. However in the installation I get these errors:

http://picload.org/image/wipocii/error.jpg

**Comment by Joncom** [comment]
@amaklp, you definitely do not want to install from NPM because it does not contain the fix. 

Instead install the latest directly from this repo like so: 
`npm install -g git+https://git@github.com/jetpack-labs/chrome-tailor.git`

**Comment by AggelosM** [comment]
@Joncom  Thanx for the help. Where do I run this? I'm now getting this:

http://picload.org/image/wipoidi/error.jpg

**Comment by Joncom** [comment]
@amaklp, perhaps you don't have Git installed? Might be necessary...

**Comment by AggelosM** [comment]
@Joncom Hmmm. Probably. Should I install [Git for Windows](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)? If so, is [this ](http://picload.org/image/wipoprw/installation.png) the correct method?

**Comment by Joncom** [comment]
@amaklp, yea. Looks good. After installing it, you should be able to type `git --version` on the command line, and it will tell you which version you have, confirming it installed correctly.

**Comment by AggelosM** [comment]
@Joncom  Thank you. I did the confirmation and git has been installed correctly.
I installed chrome tailor with the command you said and did get some warnings.
Then I tried to create the xpi and it seems it did good.

http://picload.org/image/wipicao/1.jpg

However the addon isn't working unfortunately. :(
Anyway thanx for your help!

**Comment by Joncom** [comment]
@amaklp, you're welcome.
