### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by cawa-93** [erikvold/chrome-tailor#34]
Tried to run the example:

```
~/dev/vknotice/node_modules/chrome-tailor/examples/chrome.tabs.create$ chrome-tailor xpi

Made /tmp/chromeTailor_30073GTQbbjFAdjsu
Copied chrome-tailor loader
Copied chrome extension
Creating package.json...
Wrote package.json
Creating xpi...
Unhandled rejection SyntaxError: /tmp/chromeTailor_30073GTQbbjFAdjsu/package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/chrome-tailor/lib/xpi.js:29:22
    at tryCatcher (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/async.js:180:12)
    at Async._drainQueues (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/async.js:185:10)
    at Async.drainQueues (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
```

Tried to run the my extension:

```
~/dev/vknotice/src$ chrome-tailor xpi

Made /tmp/chromeTailor_30207WcqtiR0MEkIG
Copied chrome-tailor loader
Copied chrome extension
Creating package.json...
Wrote package.json
Creating xpi...
Unhandled rejection SyntaxError: /tmp/chromeTailor_30207WcqtiR0MEkIG/package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/chrome-tailor/lib/xpi.js:29:22
    at tryCatcher (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/async.js:180:12)
    at Async._drainQueues (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/async.js:185:10)
    at Async.drainQueues (/usr/local/lib/node_modules/chrome-tailor/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)

```

**Comment by Joncom** [comment]
I to am seeing the same "package.json: Unexpected end of input" error when I try to `chrome-tailor run` a very simple Chrome extension.

_Edit 1_: 

Is #31 the same issue?

_Edit 2_: 

Apparently this issue was already fixed [here](https://github.com/jetpack-labs/chrome-tailor/commit/3ef50045554d29e1e323d2854e6d3eafb7161d43) and never made its way into an `npm` release.

_Edit 3:_

The non-working release I had installed from `npm` was version `0.0.5`. And sure enough, it's missing the above linked fix, as we can see [here](https://github.com/jetpack-labs/chrome-tailor/blob/0.0.5/lib/mk-tmp-dir.js#L47).

_Edit 4:_

I uninstalled the broken release (`npm uninstall -g chrome-tailor`) and installed the latest straight from this repository (`npm install -g git+https://git@github.com/jetpack-labs/chrome-tailor.git`).

No more "Unexpected end of input"!
